/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Meal Plan Management API
 * API to manage meals, patients, and their meal plans in a hospital.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: <your_email>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

